
FROM python:3.12

WORKDIR /app

COPY . /app/

# pymysql에 필요한 의존성 설치
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install django
WORKDIR /usr/src/app
COPY . .
WORKDIR ./todoSubject

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000