# 기본 이미지로 MySQL을 사용합니다.
FROM mysql:latest

# MySQL root 비밀번호 설정
ENV MYSQL_ROOT_PASSWORD=root_password

# MySQL 데이터베이스 생성 및 사용자 권한 설정
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*

# pymysql 설치
RUN pip3 install pymysql

# Docker 컨테이너 실행 시 실행될 명령
CMD ["mysqld"]
